= asciidoc-with-gh-pages-action

This project is a JavaScript Action that generates static websites for GitHub Pages using AsciiDoc and Handlebars templates.
It is based on the https://github.com/brettaufheber/asciidoc-site-generator#readme[asciidoc-site-generator] project.
See the documentation of this static website generator to learn more about how to set up a web project.

== Usage

First, it has to be ensured that this GitHub Action has read and *write* permissions to push changes to a dedicated branch for GitHub Pages.
Open the repository settings and navigate to "Actions", "General" and in the "Workflow Permissions" section select "Read and Write Permissions".

The link:action.yaml[action.yaml] file contains metadata about this GitHub Action and describes how to use it.

.Example CI code snippet
[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build static website
        uses: brettaufheber/asciidoc-with-gh-pages-action@v1.0.0
        with:
          domain: domain.tld
          branch: gh-pages
          user: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
----

== MIT License

Copyright (c) 2022 Eric Löffler (brettaufheber)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
